/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

/**
 *
 * @author ianka
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        btLocacao = new javax.swing.JButton();
        btDevolucao = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        cadastrarCliente = new javax.swing.JMenuItem();
        cadastrarFilme = new javax.swing.JMenuItem();
        cadastrarDVD = new javax.swing.JMenuItem();
        cadastrarCategoria = new javax.swing.JMenuItem();
        cadastrarClassificacao = new javax.swing.JMenuItem();
        cadastrarFuncionário = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenu();
        consultarCliente = new javax.swing.JMenuItem();
        consultarFilme = new javax.swing.JMenuItem();
        consultarDVD = new javax.swing.JMenuItem();
        consultarCategoria = new javax.swing.JMenuItem();
        consultarClassificacao = new javax.swing.JMenuItem();
        consultarFuncionário = new javax.swing.JMenuItem();
        menuAlterar = new javax.swing.JMenu();
        alterarCliente = new javax.swing.JMenuItem();
        alterarFilme = new javax.swing.JMenuItem();
        alterarDVD = new javax.swing.JMenuItem();
        alterarCategoria = new javax.swing.JMenuItem();
        alterarClassificacao = new javax.swing.JMenuItem();
        alterarFuncionário = new javax.swing.JMenuItem();
        menuExcluir = new javax.swing.JMenu();
        excluirCliente = new javax.swing.JMenuItem();
        excluirFilme = new javax.swing.JMenuItem();
        excluirDVD = new javax.swing.JMenuItem();
        excluirCategoria = new javax.swing.JMenuItem();
        excluirClassificacao = new javax.swing.JMenuItem();
        excluirFuncionário = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(java.awt.Color.lightGray);

        btLocacao.setText("Locação");

        btDevolucao.setText("Devolução");
        btDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDevolucaoActionPerformed(evt);
            }
        });

        btSair.setText("Sair");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btDevolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLocacao)
                    .addComponent(btDevolucao)
                    .addComponent(btSair))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        menuCadastrar.setText("Cadastrar");

        cadastrarCliente.setText("Cliente");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarCliente);

        cadastrarFilme.setText("Filme");
        cadastrarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFilmeActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarFilme);

        cadastrarDVD.setText("DVD");
        cadastrarDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarDVDActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarDVD);

        cadastrarCategoria.setText("Categoria");
        menuCadastrar.add(cadastrarCategoria);

        cadastrarClassificacao.setText("Classificação");
        menuCadastrar.add(cadastrarClassificacao);

        cadastrarFuncionário.setText("Funcionário");
        menuCadastrar.add(cadastrarFuncionário);

        jMenuBar1.add(menuCadastrar);

        menuConsultar.setText("Consultar");

        consultarCliente.setText("Cliente");
        consultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClienteActionPerformed(evt);
            }
        });
        menuConsultar.add(consultarCliente);

        consultarFilme.setText("Filme");
        consultarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarFilmeActionPerformed(evt);
            }
        });
        menuConsultar.add(consultarFilme);

        consultarDVD.setText("DVD");
        consultarDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDVDActionPerformed(evt);
            }
        });
        menuConsultar.add(consultarDVD);

        consultarCategoria.setText("Categoria");
        menuConsultar.add(consultarCategoria);

        consultarClassificacao.setText("Classificação");
        menuConsultar.add(consultarClassificacao);

        consultarFuncionário.setText("Funcionário");
        menuConsultar.add(consultarFuncionário);

        jMenuBar1.add(menuConsultar);

        menuAlterar.setText("Alterar");

        alterarCliente.setText("Cliente");
        alterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarClienteActionPerformed(evt);
            }
        });
        menuAlterar.add(alterarCliente);

        alterarFilme.setText("Filme");
        alterarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFilmeActionPerformed(evt);
            }
        });
        menuAlterar.add(alterarFilme);

        alterarDVD.setText("DVD");
        alterarDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDVDActionPerformed(evt);
            }
        });
        menuAlterar.add(alterarDVD);

        alterarCategoria.setText("Categoria");
        menuAlterar.add(alterarCategoria);

        alterarClassificacao.setText("Classificação");
        menuAlterar.add(alterarClassificacao);

        alterarFuncionário.setText("Funcionário");
        menuAlterar.add(alterarFuncionário);

        jMenuBar1.add(menuAlterar);

        menuExcluir.setText("Excluir");

        excluirCliente.setText("Cliente");
        excluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClienteActionPerformed(evt);
            }
        });
        menuExcluir.add(excluirCliente);

        excluirFilme.setText("Filme");
        excluirFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFilmeActionPerformed(evt);
            }
        });
        menuExcluir.add(excluirFilme);

        excluirDVD.setText("DVD");
        excluirDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirDVDActionPerformed(evt);
            }
        });
        menuExcluir.add(excluirDVD);

        excluirCategoria.setText("Categoria");
        menuExcluir.add(excluirCategoria);

        excluirClassificacao.setText("Classificação");
        menuExcluir.add(excluirClassificacao);

        excluirFuncionário.setText("Funcionário");
        menuExcluir.add(excluirFuncionário);

        jMenuBar1.add(menuExcluir);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDevolucaoActionPerformed

    private void cadastrarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarFilmeActionPerformed

    private void cadastrarDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarDVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarDVDActionPerformed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void consultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarClienteActionPerformed

    private void consultarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarFilmeActionPerformed

    private void consultarDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarDVDActionPerformed

    private void alterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarClienteActionPerformed

    private void alterarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarFilmeActionPerformed

    private void alterarDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarDVDActionPerformed

    private void excluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirClienteActionPerformed

    private void excluirFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirFilmeActionPerformed

    private void excluirDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirDVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirDVDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarCategoria;
    private javax.swing.JMenuItem alterarClassificacao;
    private javax.swing.JMenuItem alterarCliente;
    private javax.swing.JMenuItem alterarDVD;
    private javax.swing.JMenuItem alterarFilme;
    private javax.swing.JMenuItem alterarFuncionário;
    private javax.swing.JButton btDevolucao;
    private javax.swing.JButton btLocacao;
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem cadastrarCategoria;
    private javax.swing.JMenuItem cadastrarClassificacao;
    private javax.swing.JMenuItem cadastrarCliente;
    private javax.swing.JMenuItem cadastrarDVD;
    private javax.swing.JMenuItem cadastrarFilme;
    private javax.swing.JMenuItem cadastrarFuncionário;
    private javax.swing.JMenuItem consultarCategoria;
    private javax.swing.JMenuItem consultarClassificacao;
    private javax.swing.JMenuItem consultarCliente;
    private javax.swing.JMenuItem consultarDVD;
    private javax.swing.JMenuItem consultarFilme;
    private javax.swing.JMenuItem consultarFuncionário;
    private javax.swing.JMenuItem excluirCategoria;
    private javax.swing.JMenuItem excluirClassificacao;
    private javax.swing.JMenuItem excluirCliente;
    private javax.swing.JMenuItem excluirDVD;
    private javax.swing.JMenuItem excluirFilme;
    private javax.swing.JMenuItem excluirFuncionário;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAlterar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuConsultar;
    private javax.swing.JMenu menuExcluir;
    // End of variables declaration//GEN-END:variables
}
