/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Locacao.ConsultaDevolucao;
import Locacao.ControleLocacao;
import Visao.Alterar.AlterarCategoria;
import Visao.Alterar.AlterarClassificacao;
import Visao.Alterar.AlterarCliente;
import Visao.Alterar.AlterarFilme;
import Visao.Alterar.AlterarFuncionario;
import Visao.Cadastrar.CadastrarCategoria;
import Visao.Cadastrar.CadastrarClassificacao;
import Visao.Cadastrar.CadastrarCliente;
import Visao.Cadastrar.CadastrarFilme;
import Visao.Cadastrar.CadastrarFuncionario;
import Visao.Consultar.ConsultarCategoria;
import Visao.Consultar.ConsultarClassificacao;
import Visao.Consultar.ConsultarCliente;
import Visao.Consultar.ConsultarFilme;
import Visao.Consultar.ConsultarFuncionario;
import Visao.Excluir.ExcluirCategoria;
import Visao.Excluir.ExcluirClassificacao;
import Visao.Excluir.ExcluirCliente;
import Visao.Excluir.ExcluirFilme;
import Visao.Excluir.ExcluirFuncionario;

/**
 *
 * @author ianka
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle("LocVideo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        btLocacao = new javax.swing.JButton();
        btDevolucao = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        cadastrarCliente = new javax.swing.JMenuItem();
        cadastrarFilme = new javax.swing.JMenuItem();
        cadastrarCategoria = new javax.swing.JMenuItem();
        cadastrarClassificacao = new javax.swing.JMenuItem();
        cadastrarFuncionário = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenu();
        consultarCliente = new javax.swing.JMenuItem();
        consultarFilme = new javax.swing.JMenuItem();
        consultarCategoria = new javax.swing.JMenuItem();
        consultarClassificacao = new javax.swing.JMenuItem();
        consultarFuncionário = new javax.swing.JMenuItem();
        menuAlterar = new javax.swing.JMenu();
        alterarCliente = new javax.swing.JMenuItem();
        alterarFilme = new javax.swing.JMenuItem();
        alterarCategoria = new javax.swing.JMenuItem();
        alterarClassificacao = new javax.swing.JMenuItem();
        alterarFuncionário = new javax.swing.JMenuItem();
        menuExcluir = new javax.swing.JMenu();
        excluirCliente = new javax.swing.JMenuItem();
        excluirFilme = new javax.swing.JMenuItem();
        excluirCategoria = new javax.swing.JMenuItem();
        excluirClassificacao = new javax.swing.JMenuItem();
        excluirFuncionário = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        relatorioAlugueis = new javax.swing.JMenuItem();
        relatorioCaixa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(java.awt.Color.lightGray);

        btLocacao.setText("Locação");
        btLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocacaoActionPerformed(evt);
            }
        });

        btDevolucao.setText("Devolução");
        btDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDevolucaoActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btDevolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLocacao)
                    .addComponent(btDevolucao)
                    .addComponent(btSair))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        menuCadastrar.setText("Cadastrar");

        cadastrarCliente.setText("Cliente");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarCliente);

        cadastrarFilme.setText("Filme");
        cadastrarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFilmeActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarFilme);

        cadastrarCategoria.setText("Categoria");
        cadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCategoriaActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarCategoria);

        cadastrarClassificacao.setText("Classificação");
        cadastrarClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClassificacaoActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarClassificacao);

        cadastrarFuncionário.setText("Funcionário");
        cadastrarFuncionário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionárioActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarFuncionário);

        jMenuBar1.add(menuCadastrar);

        menuConsultar.setText("Consultar");

        consultarCliente.setText("Cliente");
        consultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClienteActionPerformed(evt);
            }
        });
        menuConsultar.add(consultarCliente);

        consultarFilme.setText("Filme");
        consultarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarFilmeActionPerformed(evt);
            }
        });
        menuConsultar.add(consultarFilme);

        consultarCategoria.setText("Categoria");
        consultarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCategoriaActionPerformed(evt);
            }
        });
        menuConsultar.add(consultarCategoria);

        consultarClassificacao.setText("Classificação");
        consultarClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClassificacaoActionPerformed(evt);
            }
        });
        menuConsultar.add(consultarClassificacao);

        consultarFuncionário.setText("Funcionário");
        consultarFuncionário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarFuncionárioActionPerformed(evt);
            }
        });
        menuConsultar.add(consultarFuncionário);

        jMenuBar1.add(menuConsultar);

        menuAlterar.setText("Alterar");

        alterarCliente.setText("Cliente");
        alterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarClienteActionPerformed(evt);
            }
        });
        menuAlterar.add(alterarCliente);

        alterarFilme.setText("Filme");
        alterarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFilmeActionPerformed(evt);
            }
        });
        menuAlterar.add(alterarFilme);

        alterarCategoria.setText("Categoria");
        alterarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarCategoriaActionPerformed(evt);
            }
        });
        menuAlterar.add(alterarCategoria);

        alterarClassificacao.setText("Classificação");
        alterarClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarClassificacaoActionPerformed(evt);
            }
        });
        menuAlterar.add(alterarClassificacao);

        alterarFuncionário.setText("Funcionário");
        alterarFuncionário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFuncionárioActionPerformed(evt);
            }
        });
        menuAlterar.add(alterarFuncionário);

        jMenuBar1.add(menuAlterar);

        menuExcluir.setText("Excluir");

        excluirCliente.setText("Cliente");
        excluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClienteActionPerformed(evt);
            }
        });
        menuExcluir.add(excluirCliente);

        excluirFilme.setText("Filme");
        excluirFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFilmeActionPerformed(evt);
            }
        });
        menuExcluir.add(excluirFilme);

        excluirCategoria.setText("Categoria");
        excluirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCategoriaActionPerformed(evt);
            }
        });
        menuExcluir.add(excluirCategoria);

        excluirClassificacao.setText("Classificação");
        excluirClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClassificacaoActionPerformed(evt);
            }
        });
        menuExcluir.add(excluirClassificacao);

        excluirFuncionário.setText("Funcionário");
        excluirFuncionário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFuncionárioActionPerformed(evt);
            }
        });
        menuExcluir.add(excluirFuncionário);

        jMenuBar1.add(menuExcluir);

        menuRelatorio.setText("Relatórios");

        relatorioAlugueis.setText("Alugueis");
        relatorioAlugueis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioAlugueisActionPerformed(evt);
            }
        });
        menuRelatorio.add(relatorioAlugueis);

        relatorioCaixa.setText("Caixa");
        menuRelatorio.add(relatorioCaixa);

        jMenuBar1.add(menuRelatorio);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDevolucaoActionPerformed
        // TODO add your handling code here:
        new ConsultaDevolucao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDevolucaoActionPerformed

    private void cadastrarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFilmeActionPerformed
        // TODO add your handling code here:
        new CadastrarFilme().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarFilmeActionPerformed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        // TODO add your handling code here:
        new CadastrarCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void consultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarClienteActionPerformed
        // TODO add your handling code here:
        new ConsultarCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultarClienteActionPerformed

    private void consultarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarFilmeActionPerformed
        // TODO add your handling code here:
        new ConsultarFilme().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultarFilmeActionPerformed

    private void alterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarClienteActionPerformed
        // TODO add your handling code here:
        new AlterarCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alterarClienteActionPerformed

    private void alterarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFilmeActionPerformed
        // TODO add your handling code here:
        new AlterarFilme().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alterarFilmeActionPerformed

    private void excluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirClienteActionPerformed
        // TODO add your handling code here:
        new ExcluirCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_excluirClienteActionPerformed

    private void excluirFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirFilmeActionPerformed
        // TODO add your handling code here:
        new ExcluirFilme().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_excluirFilmeActionPerformed

    private void cadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCategoriaActionPerformed
        // TODO add your handling code here:
        new CadastrarCategoria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarCategoriaActionPerformed

    private void cadastrarClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClassificacaoActionPerformed
        // TODO add your handling code here:
        new CadastrarClassificacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarClassificacaoActionPerformed

    private void cadastrarFuncionárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionárioActionPerformed
        // TODO add your handling code here:
        new CadastrarFuncionario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarFuncionárioActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void excluirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCategoriaActionPerformed
        // TODO add your handling code here:
        new ExcluirCategoria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_excluirCategoriaActionPerformed

    private void excluirClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirClassificacaoActionPerformed
        // TODO add your handling code here:
        new ExcluirClassificacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_excluirClassificacaoActionPerformed

    private void excluirFuncionárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirFuncionárioActionPerformed
        // TODO add your handling code here:
        new ExcluirFuncionario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_excluirFuncionárioActionPerformed

    private void consultarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCategoriaActionPerformed
        // TODO add your handling code here:
        new ConsultarCategoria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultarCategoriaActionPerformed

    private void consultarClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarClassificacaoActionPerformed
        // TODO add your handling code here:
        new ConsultarClassificacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultarClassificacaoActionPerformed

    private void consultarFuncionárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarFuncionárioActionPerformed
        // TODO add your handling code here:
        new ConsultarFuncionario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultarFuncionárioActionPerformed

    private void alterarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarCategoriaActionPerformed
        // TODO add your handling code here:
        new AlterarCategoria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alterarCategoriaActionPerformed

    private void alterarClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarClassificacaoActionPerformed
        // TODO add your handling code here:
        new AlterarClassificacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alterarClassificacaoActionPerformed

    private void alterarFuncionárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFuncionárioActionPerformed
        // TODO add your handling code here:
        new AlterarFuncionario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alterarFuncionárioActionPerformed

    private void btLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocacaoActionPerformed
        // TODO add your handling code here:
        new ControleLocacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLocacaoActionPerformed

    private void relatorioAlugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioAlugueisActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_relatorioAlugueisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarCategoria;
    private javax.swing.JMenuItem alterarClassificacao;
    private javax.swing.JMenuItem alterarCliente;
    private javax.swing.JMenuItem alterarFilme;
    private javax.swing.JMenuItem alterarFuncionário;
    private javax.swing.JButton btDevolucao;
    private javax.swing.JButton btLocacao;
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem cadastrarCategoria;
    private javax.swing.JMenuItem cadastrarClassificacao;
    private javax.swing.JMenuItem cadastrarCliente;
    private javax.swing.JMenuItem cadastrarFilme;
    private javax.swing.JMenuItem cadastrarFuncionário;
    private javax.swing.JMenuItem consultarCategoria;
    private javax.swing.JMenuItem consultarClassificacao;
    private javax.swing.JMenuItem consultarCliente;
    private javax.swing.JMenuItem consultarFilme;
    private javax.swing.JMenuItem consultarFuncionário;
    private javax.swing.JMenuItem excluirCategoria;
    private javax.swing.JMenuItem excluirClassificacao;
    private javax.swing.JMenuItem excluirCliente;
    private javax.swing.JMenuItem excluirFilme;
    private javax.swing.JMenuItem excluirFuncionário;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAlterar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuConsultar;
    private javax.swing.JMenu menuExcluir;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem relatorioAlugueis;
    private javax.swing.JMenuItem relatorioCaixa;
    // End of variables declaration//GEN-END:variables
}
