/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Consultar;

import DAO.CategoriaDAO;
import DAO.ClassificacaoDAO;
import DAO.Conexao;
import DAO.FilmeDAO;
import Modelo.Categoria;
import Modelo.Classificacao;
import Modelo.Filme;
import Principal.Menu;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ianka
 */
public class ConsultarFilme extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarFilme
     */
    public ConsultarFilme() {
        initComponents();
        setTitle("LocVideo");
        setSize(1200, 400);
        AtualizaTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        btOKTitulo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfCod = new javax.swing.JTextField();
        btOKCod = new javax.swing.JButton();
        btTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFilme = new javax.swing.JTable();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jInternalFrame1.setVisible(true);

        jLabel1.setText("Pesquisar por Titulo:");

        btOKTitulo.setText("OK");
        btOKTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKTituloActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisar por Código:");

        btOKCod.setText("OK");
        btOKCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKCodActionPerformed(evt);
            }
        });

        btTodos.setText("TODOS");
        btTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTodosActionPerformed(evt);
            }
        });

        jTableFilme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Titulo", "Ano", "Duração", "Categoria", "Classificação", "Preço de Compra", "Data da Compra", "Quantidade em Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFilme);

        btVoltar.setText("Voltar ao Menu");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOKTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOKCod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btTodos)
                .addGap(23, 23, 23))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOKTitulo)
                    .addComponent(jLabel2)
                    .addComponent(tfCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOKCod)
                    .addComponent(btTodos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizaTable(){
        Connection con = Conexao.AbrirConexao();
        FilmeDAO bd = new FilmeDAO(con);
        CategoriaDAO sql = new CategoriaDAO(con);
        ClassificacaoDAO sql2 = new ClassificacaoDAO(con);
        List<Filme> lista = new ArrayList<>();
        List<Categoria> lista2 = new ArrayList<>();
        List<Classificacao> lista3 = new ArrayList<>();
        lista = bd.ListarFilme();
        DefaultTableModel tbm = (DefaultTableModel) jTableFilme.getModel();
        while(tbm.getRowCount() > 0){
            tbm.removeRow(0);
        }
        int i = 0;
        for(Filme a : lista){
            tbm.addRow(new String[i]);
            jTableFilme.setValueAt(a.getCodigo(), i, 0);
            jTableFilme.setValueAt(a.getTitulo(), i, 1);
            jTableFilme.setValueAt(a.getAno(), i, 2);
            jTableFilme.setValueAt(a.getDuracao(), i, 3);
            lista2 = sql.Pesquisar_Cod_Categoria(a.getCod_categoria());
            for(Categoria b : lista2){
                jTableFilme.setValueAt(b.getNome(), i, 4);
            }
            lista3 = sql2.Pesquisar_Cod_Classificacao(a.getCod_classificacao());
            for(Classificacao c : lista3){
                jTableFilme.setValueAt(c.getNome(), i, 5);
            }
            jTableFilme.setValueAt(a.getPreco_compra(), i, 6);
            jTableFilme.setValueAt(a.getData_compra(), i, 7);
            jTableFilme.setValueAt(a.getQtdEstoque(), i, 8);
            i++;
        }
        Conexao.FecharConexao(con);
    }
    
    private void btTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTodosActionPerformed
        // TODO add your handling code here:
        AtualizaTable();
    }//GEN-LAST:event_btTodosActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btOKTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKTituloActionPerformed
        // TODO add your handling code here:
        String titulo = tfTitulo.getText();
        Connection con = Conexao.AbrirConexao();
        FilmeDAO bd = new FilmeDAO(con);
        CategoriaDAO sql = new CategoriaDAO(con);
        ClassificacaoDAO sql2 = new ClassificacaoDAO(con);
        if(titulo.equals("")){
            JOptionPane.showMessageDialog(null, "Digite o Titulo a ser Pesquisado", 
                    "LocVideo", JOptionPane.WARNING_MESSAGE);
        }
        List<Filme> lista = new ArrayList<>();
        List<Categoria> lista2 = new ArrayList<>();
        List<Classificacao> lista3 = new ArrayList<>();
        lista = bd.Pesquisar_Titulo_Filme(titulo);
        DefaultTableModel tbm = (DefaultTableModel) jTableFilme.getModel();
        while(tbm.getRowCount() > 0){
            tbm.removeRow(0);
        }
        int i = 0;
        for(Filme a : lista){
            tbm.addRow(new String[i]);
            jTableFilme.setValueAt(a.getCodigo(), i, 0);
            jTableFilme.setValueAt(a.getTitulo(), i, 1);
            jTableFilme.setValueAt(a.getAno(), i, 2);
            jTableFilme.setValueAt(a.getDuracao(), i, 3);
            lista2 = sql.Pesquisar_Cod_Categoria(a.getCod_categoria());
            for(Categoria b : lista2){
                jTableFilme.setValueAt(b.getNome(), i, 4);
            }
            lista3 = sql2.Pesquisar_Cod_Classificacao(a.getCod_classificacao());
            for(Classificacao c : lista3){
                jTableFilme.setValueAt(c.getNome(), i, 5);
            }
            jTableFilme.setValueAt(a.getPreco_compra(), i, 6);
            jTableFilme.setValueAt(a.getData_compra(), i, 7);
            jTableFilme.setValueAt(a.getQtdEstoque(), i, 8);
            i++;
        }
        Conexao.FecharConexao(con);
        tfTitulo.setText("");
    }//GEN-LAST:event_btOKTituloActionPerformed

    private void btOKCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKCodActionPerformed
        // TODO add your handling code here:
        String codigo = tfCod.getText();
        if(codigo.equals("")){
            JOptionPane.showMessageDialog(null, "Digite um código a ser pesquisado", 
                    "LocVideo", JOptionPane.WARNING_MESSAGE);
        }else{
            int cod = Integer.parseInt(codigo);
            Connection con = Conexao.AbrirConexao();
            FilmeDAO bd = new FilmeDAO(con);
            CategoriaDAO sql = new CategoriaDAO(con);
            ClassificacaoDAO sql2 = new ClassificacaoDAO(con);
            List<Filme> lista = new ArrayList<>();
            List<Categoria> lista2 = new ArrayList<>();
            List<Classificacao> lista3 = new ArrayList<>();
            lista = bd.Pesquisar_Cod_Filme(cod);
            DefaultTableModel tbm = (DefaultTableModel) jTableFilme.getModel();
            while(tbm.getRowCount() > 0){
                tbm.removeRow(0);
            }
            int i = 0;
            for(Filme a : lista){
                tbm.addRow(new String[i]);
                jTableFilme.setValueAt(a.getCodigo(), i, 0);
                jTableFilme.setValueAt(a.getTitulo(), i, 1);
                jTableFilme.setValueAt(a.getAno(), i, 2);
                jTableFilme.setValueAt(a.getDuracao(), i, 3);
                lista2 = sql.Pesquisar_Cod_Categoria(a.getCod_categoria());
                for(Categoria b : lista2){
                    jTableFilme.setValueAt(b.getNome(), i, 4);
                }
                lista3 = sql2.Pesquisar_Cod_Classificacao(a.getCod_classificacao());
                for(Classificacao c : lista3){
                    jTableFilme.setValueAt(c.getNome(), i, 5);
                }
                jTableFilme.setValueAt(a.getPreco_compra(), i, 6);
                jTableFilme.setValueAt(a.getData_compra(), i, 7);
                jTableFilme.setValueAt(a.getQtdEstoque(), i, 8);
                i++;
            }
            Conexao.FecharConexao(con);
            tfCod.setText("");
        }
    }//GEN-LAST:event_btOKCodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOKCod;
    private javax.swing.JButton btOKTitulo;
    private javax.swing.JButton btTodos;
    private javax.swing.JButton btVoltar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFilme;
    private javax.swing.JTextField tfCod;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
